-- データベースの作成
CREATE DATABASE IF NOT EXISTS memo_app;

-- データベースを使用
USE memo_app;

-- Userテーブルの作成
CREATE TABLE IF NOT EXISTS User (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    discord_id VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Noteテーブルの作成
CREATE TABLE IF NOT EXISTS Note (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT UNSIGNED NOT NULL,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES User(id) ON DELETE CASCADE
);

ALTER TABLE User ADD COLUMN username VARCHAR(100) NOT NULL;
